# clash config file

# Port of HTTP(S) proxy server on the local end
port: 8080

# Port of SOCKS5 proxy server on the local end
socks-port: 8085

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

allow-lan: true

bind-address: "*"

mode: rule

# info / warning / error / debug / silent
log-level: info

ipv6: false

profile:
  store-selected: false

dns:
  enable: false

# proxies:

proxy-providers:
  global:
    type: http
    url: "https://proxypooliu.herokuapp.com/clash/proxies"
    interval: 3600
    path: ./provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  zh:
    type: http
    url: "https://proxypool.fly.dev/clash/proxies?c=CN,HK,TW"
    interval: 3600
    path: ./provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  oversea:
    type: http
    url: "https://proxypool.fly.dev/clash/proxies?nc=CN&filter=1" # filter out pool
    #  https://proxypool.fly.dev/clash/proxies?nc=CN
    interval: 3600
    path: ./provider.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  # url-test select which proxy will be used by benchmarking speed to a URL.
  - name: "fq"
    type: fallback
    use:
      - oversea
      - global
    lazy: true
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  # fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
  - name: "anti-anti-crawler"
    type: load-balance
    use:
      - zh
      - oversea
      - global
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    # use round robin to request the url via random proxies
    # or consistent-hashing will request same url via same proxy
    strategy: round-robin

  - name: "auto"
    type: fallback
    use:
      - oversea
      - zh
      - global
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rules:
  # bypass cn and local
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - GEOIP,CN,DIRECT

  #hot blocked site
  - DOMAIN-SUFFIX,google.com,fq
  - DOMAIN-KEYWORD,google,fq
  - DOMAIN,google.com,fq
  - DOMAIN-KEYWORD,wikipedia,fq
  - DOMAIN-KEYWORD,facebook,fq
  - DOMAIN-KEYWORD,intgram,fq
  - DOMAIN-KEYWORD,telegram,fq
  - DOMAIN,rsshub.app,fq

  # anti cloudflare
  - IP-CIDR,103.21.244.0/22,anti-anti-crawler
  - IP-CIDR,103.22.200.0/22,anti-anti-crawler
  - IP-CIDR,103.31.4.0/22,anti-anti-crawler
  - IP-CIDR,104.16.0.0/13,anti-anti-crawler
  - IP-CIDR,104.24.0.0/14,anti-anti-crawler
  - IP-CIDR,108.162.192.0/18,anti-anti-crawler
  - IP-CIDR,131.0.72.0/22,anti-anti-crawler
  - IP-CIDR,141.101.64.0/18,anti-anti-crawler
  - IP-CIDR,162.158.0.0/15,anti-anti-crawler
  - IP-CIDR,172.64.0.0/13,anti-anti-crawler
  - IP-CIDR,173.245.48.0/20,anti-anti-crawler
  - IP-CIDR,188.114.96.0/20,anti-anti-crawler
  - IP-CIDR,190.93.240.0/20,anti-anti-crawler
  - IP-CIDR,197.234.240.0/22,anti-anti-crawler
  - IP-CIDR,198.41.128.0/17,anti-anti-crawler

  # common not available region
  - DOMAIN-KEYWORD,tw,fq
  - DOMAIN-KEYWORD,hk,fq
  - GEOIP,TW,fq
  - GEOIP,US,fq

  # anti anti crawler
  - DOMAIN-KEYWORD,wechat,anti-anti-crawler
  - DOMAIN-KEYWORD,wexin,anti-anti-crawler
  - DOMAIN,wemp.app,anti-anti-crawler
  - DOMAIN,ershicimi.com,anti-anti-crawler

  - MATCH,auto
