# clash config file
# version 1.7
# last update 2021-08-15

# Port of HTTP(S) proxy server on the local end
port: 8080

# Port of SOCKS5 proxy server on the local end
socks-port: 8085

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS5 server on the same port
# mixed-port: 7890

allow-lan: true

bind-address: "*"

mode: rule

# info / warning / error / debug / silent
log-level: info

ipv6: false

profile:
  store-selected: false

dns:
  enable: false

# proxies:

proxy-providers:
  global:
    type: http
    #    url: "https://proxypooliu.herokuapp.com/clash/proxies"
    #    url: "https://cdn.jsdelivr.net/gh/guoxing123/xingxing/clash1123.yaml"
    #    url: "https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fssrsub%2Fssr%2FClash.yml&target=clash"
    url: "https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fssrsub%2Fssr%2FClash.yml&target=clash"
    interval: 3600
    path: ./cdn.jsdelivr.net.yaml
    health-check:
      enable: true
      interval: 600
      #      url: http://www.gstatic.com/generate_204
      url: "https://www.google.com/robots.txt"

  global2:
    type: http
    url: "https://klausvpn.posyao.com/clash/proxies?nc=CN&speed=1"
    interval: 3600
    path: ./klausvpn.posyao.com.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  global3: # won't update
    type: http
    url: "https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fv2raydy%2FClash%40main%2F02-22u2.yaml&target=clash"
    interval: 3600
    path: ./cdn.jsdelivr.net.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  global4: # won't update
    type: http
    url: "https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fraw.githubusercontent.com%2Fchangfengoss%2Fpub%2Fmain%2Fdata%2F2022_05_07%2FWftZxZ.yaml&target=clash"
    interval: 3600
    path: ./raw.githubusercontent.com.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  global5: # limited
    type: http
    url: "https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Ftsd.ink%2Ffree&target=clash"
    interval: 3600
    path: ./tsd.ink.yaml
    health-check:
      enable: true
      interval: 600
      url: https://www.gstatic.com/generate_204

  oversea:
    type: http
    url: "https://proxy-provider-converter.vercel.app/api/convert?url=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fguoxing123%2Fxingxing%2Fclash1123.yaml&target=clash"
    interval: 3600
    path: ./cdn.jsdelivr.net.yaml
    health-check:
      enable: true
      interval: 600
      url: "https://www.google.com/robots.txt"

proxy-groups:
  # url-test select which proxy will be used by benchmarking speed to a URL.
  # fallback selects an available policy by priority. The availability is tested by accessing an URL, just like an auto url-test group.
  - name: "fq"
    type: fallback
    use:
      - global
      - global2
      - global5
      - global3
      - global4
      - oversea
    # lazy: true
    url: "https://www.google.com/robots.txt"
    interval: 100

  - name: "global-random"
    type: load-balance
    use:
      - oversea
      - global
      - global2
      - global3
      - global4
      - global5
    proxies:
      - DIRECT
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    # use round robin to request the url via random proxies
    # or consistent-hashing will request same url via same proxy
    strategy: round-robin

rules:
  # bypass local
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT

  # hot blocked site
  - DOMAIN-KEYWORD,google,fq
  - DOMAIN-KEYWORD,wikipedia,fq
  - DOMAIN-KEYWORD,facebook,fq
  - DOMAIN-KEYWORD,intgram,fq
  - DOMAIN-KEYWORD,telegram,fq
  - DOMAIN,rsshub.app,fq

  # anti cloudflare
  - IP-CIDR,103.21.244.0/22,global-random
  - IP-CIDR,103.22.200.0/22,global-random
  - IP-CIDR,103.31.4.0/22,global-random
  - IP-CIDR,104.16.0.0/13,global-random
  - IP-CIDR,104.24.0.0/14,global-random
  - IP-CIDR,108.162.192.0/18,global-random
  - IP-CIDR,131.0.72.0/22,global-random
  - IP-CIDR,141.101.64.0/18,global-random
  - IP-CIDR,162.158.0.0/15,global-random
  - IP-CIDR,172.64.0.0/13,global-random
  - IP-CIDR,173.245.48.0/20,global-random
  - IP-CIDR,188.114.96.0/20,global-random
  - IP-CIDR,190.93.240.0/20,global-random
  - IP-CIDR,197.234.240.0/22,global-random
  - IP-CIDR,198.41.128.0/17,global-random

  # anti anti crawler
  - DOMAIN-KEYWORD,wechat,global-random
  - DOMAIN-KEYWORD,wexin,global-random
  - DOMAIN-KEYWORD,douban,global-random
  - DOMAIN,wemp.app,global-random
  - DOMAIN,ershicimi.com,global-random
  - DOMAIN,segmentfault.com,global-random

  # default
  - GEOIP,CN,DIRECT
  - MATCH,global-random
