# update time 2021-05-08
# version 2.0
version: "3.5"
services:
  ######################
  ##   Applications   ##
  ######################

  app.ttrss:
    image: wangqiru/ttrss
    container_name: ttrss
    depends_on:
      - database.ttrss
    ports:
      - 777:80/tcp
    environment:
      - SELF_URL_PATH=http://rss.colinx.one:777/ # !!!please change to your own domain!!!

      # database settings
      - DB_HOST=database.ttrss
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=%%Password_HERE%% # please change the password
      - ENABLE_PLUGINS=auth_internal,fever
    networks:
      - net_public
      - net_private
    volumes:
      - feed-favicons:/var/www/feed-icons/
      - starred-images:/var/www/cache/starred-images/
      - plugins:/var/www/app/plugins.local/
      - themes:/var/www/app/themes.local/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true
    command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'
    labels:
      - one.colinx.rssmanx.description='Tiny Tiny RSS is a free and open source web-based news feed (RSS/Atom) reader and aggregator'
    restart: always

  ######################
  ##     Databases    ##
  ######################

  database.ttrss:
    image: postgres:13-alpine # Lock major version
    container_name: ttrss_db
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=%%Password_HERE%% # please change the password
    volumes:
      - ~/.dockerData/Database/DBttrss/:/var/lib/postgresql/data # persist postgres data
    networks:
      - net_private
 
    restart: always
    labels:
      - one.colinx.rssmanx.description='Database of Tiny Tiny RSS service'

  ######################
  ##     Services     ##
  ######################

  service.rsshub:
    image: diygod/rsshub
    container_name: rsshub
    depends_on:
      - service.redis

    restart: always
    # ports:
    #     - '1200:1200'
    environment:
      - PORT=80
      # miscellaneous settings
      - NODE_ENV=production
    expose:
      - 80
    networks:
      - net_public
      - net_private
    dns:
      - 223.5.5.5
      - 8.8.8.8
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - one.colinx.rssmanx.description='RSShub makes everything rssable'

 
volumes:
  redis-data:
  feed-favicons:
  starred-images:
  plugins:
  themes:

networks:
  net_public:
  net_private:
    internal: true
