# update time 2022-05-11
# rssman version 3.3
version: "3.5"
services:
  ######################
  ##   Applications   ##
  ######################
  app.ttrss:
    image: wangqiru/ttrss
    container_name: ttrss
    depends_on:
      - database.ttrss
    ports:
      - ${TTRSS_PORT:-10080}:80/tcp # change the port if you need
    environment:
      - SELF_URL_PATH=${TTRSS_SELF_URL:?'The TTRSS self url value is needed'} # please change to your own domain
      - DISABLE_USER_IN_DAYS=14
      - ALLOW_PORTS=${RSS_ALLOW_PORTS:-'80,443,3000'}
      # database settings
      - DB_HOST=database.ttrss
      - DB_PORT=5432
      - DB_NAME=ttrss
      - DB_USER=postgres
      - DB_PASS=${DB_Password:-pass_for_DB} # please change the password
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required.
    networks:
      - net_public
      - net_private
    volumes:
      - feed-favicons:/var/www/feed-icons/
      - starred-images:/var/www/cache/starred-images/
      - plugins:/var/www/app/plugins.local/
      - themes:/var/www/app/themes.local/
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true
    labels:
      - one.colinx.rssmanx.description='Tiny Tiny RSS is a free and open source web-based news feed (RSS/Atom) reader and aggregator'
    restart: always

  ######################
  ##     Databases    ##
  ######################
  database.ttrss:
    image: postgres:13-alpine # Lock major version
    container_name: ttrss_db
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=${DB_Password:-pass_for_DB} # feel free to change the password
    volumes:
      - ${DB_DIR:-~/.docker/Database}/DBttrss/:/var/lib/postgresql/data # persist db data
    networks:
      - net_private
    restart: always
    labels:
      - one.colinx.rssmanx.description='Database of Tiny Tiny RSS service'

  ######################
  ##     Services     ##
  ######################

  service.rsshub:
    image: diygod/rsshub
    container_name: rsshub
    depends_on:
      - service.redis
    restart: on-failure:5
    # ports:
    #     - '1200:1200'
    environment:
      - PORT=80
      # miscellaneous settings
      - NODE_ENV=production
    expose:
      - 80
    networks:
      - net_public
      - net_private
    dns:
      - 223.5.5.5
      - 8.8.8.8
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      - one.colinx.rssmanx.description='RSShub makes everything rssable'

volumes:
  feed-favicons:
  starred-images:
  plugins:
  themes:

networks:
  net_public:
  net_private:
    internal: true
